[package]
name = "rusty-keys"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tempfile = "3.23.0"
clap = { version = "4.6.1", features = ["derive"] }
serde-jsonlines = "0.7.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"

[dev-dependencies]
assert_matches_regex = "0.1"
